MVC 2단계 구현(ModelAndView, Controller, DispatcherServlet)
code-squad/java-framework pull request #1
Opened 2017-10-30 01:34 UTC by seulgiwendy

2단계까지의 구현을 마쳤습니다.

2017-10-30 02:36 UTC, javajigi requested changes

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/mvc/controller/CreateUserController.java
> +	}
다음과 같이 User 객체 내에서 유효성 체크를 하면 어떨까?

```
public class User {

    private Integer id;
    private String firstName;
    private String sex; // I'm ready when you are :P

    /**
    * ... All Your Getters and Setters Here
    */

    public boolean validate() {
        if (this.firstName == null) {
            return false;
        }
        if (this.sex == null) {
            return false;
        }
        return true;
    }
```

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/mvc/controller/LoginController.java
> +		return new ModelAndView(new JspView("/user/login.jsp"));
특별한 로직이 없는 Controller의 경우에도 Controller를 추가하는 것은 불합리하다는 생각이 든다.
이와 같이 로직이 없는 Controller는 어떻게 처리하면 좋을까?

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/mvc/controller/LoginPostController.java
> +			System.err.println("someone just logined by using HttpSession.");
Logger의 error 사용할 것을 추천

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/mvc/controller/UpdateUserController.java
> +		User updateUser = new User(req.getParameter("userId"), req.getParameter("password"), req.getParameter("name"),
수정하는 시점에는 유효성 체크를 하지 않는가?

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/mvc/requestmapping/RequestMapping.java
> +	private static RequestMapping rm;
private static final RequestMapping rm = new RequestMapping() 과 같이 구현하면 어떨까?
기존 구현과의 차이점은?

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/web/requestservlet/DispatcherServlet.java
> +			System.err.println("No Controllers Found.");
res 사용해 404 응답을 보내도록 구현하면 더 좋겠네.

2017-10-30 02:36 UTC, javajigi commented on src/main/java/core/web/requestservlet/DispatcherServlet.java
> +	private RequestLine generateRequestLine(String path, RequestMethod method) {
HttpServletRequest를 인자로 받는 것은 어떨까?

2017-10-30 03:18 UTC, seulgiwendy commented on src/main/java/core/mvc/requestmapping/RequestMapping.java
> +	private static RequestMapping rm;
RequestMapping이 메모리에 적재될 시점에 자동으로 하나를 만들어서 가지고 있는 Eager 초기화 방식이 될 것 같습니다. 제가 지금 구현한 방식은 실제 RequestMapping 객체가 필요해질 때 초기화하는 lazy 방식인데 어차피 DispatcherServlet의 init()에서 항상 실행되므로 차이는 없을 것 같습니다.

2017-10-31 11:48 UTC, seulgiwendy commented
JDBC 리팩토링까지 마쳤습니다.

2017-11-01 01:58 UTC, javajigi requested changes

2017-11-01 01:58 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +	public JdbcManager(String sql) {
이와 같이 구현할 경우 매번 JdbcManager 인스턴스를 매번 생성해야 함.
메소드의 인자로 sql 전달할 경우 JdbcManager 인스턴스를 하나만 생성해 재사용할 수 있음. singleton 패턴 적용 가능..

2017-11-01 01:58 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +		try {
try-with-resources 구문을 활용하면 finally 절을 제거할 수 있음.

2017-11-01 01:58 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +			e.printStackTrace(System.out);
Exception을 catch 한 후 아무런 조치도 취하지 않을 경우 사용자에게 에러 메시지를 전달할 방법이 없음.

2017-11-01 01:58 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +		return null;
만약 Exception이 발생했을 때 null을 반환하고 싶다면 catch에서 하면 됨.

2017-11-01 01:58 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +	public void insertObject(PreparedStatementSetter pstmts) throws SQLException {
SQLException은 compile time exception이라 이와 같이 구현할 경우 이 메소드를 사용하는 모든 메소드가 매번 try/catch를 구현해야 함.
compile time exception을 run time exception을 변환한 후 throw할 것을 추천함.

2017-11-01 01:58 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +	public List<User> findAll(RowMapper<List<User>> rm) {
앞의 find 메소드와 중복이 많음. 중복을 제거해 보면 좋겠음.

2017-11-01 01:58 UTC, javajigi commented on src/main/java/next/dao/UserDao.java
> +			while (rs.next()) {
while(rs.next()) 문도 제거할 수 있도록 라이브러리 개선

2017-11-02 02:50 UTC, seulgiwendy commented
중복을 제거하고 Generic을 사용해 User와의 종속성을 모두 끊었습니다.

2017-11-03 02:24 UTC, merged