DI 프레임워크 중간점검
code-squad/java-framework pull request #28
Opened 2017-11-13 08:51 UTC by seulgiwendy

코드를 중간 리뷰받고 마무리하겠습니다.

2017-11-13 09:36 UTC, javajigi requested changes
전체적으로 코드 구현이 깔끔하게 잘 되었다.
DI 프레임워크와 ORM 프레임워크 연동까지 된다면 정말 엄청난 녀석이 만들어질 수 있겠다.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanFactory.java
> +		.forEach(b -> {
{} 없이 한 라인으로 구현해도 되겠다.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanFactory.java
> +			return this.beans.values().stream().filter(b -> clazz.isAssignableFrom(b.getClass())).findFirst()
stream과 optional 사용의 끝판왕인가? 대단하이

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanFactory.java
> +
굳이 공백을 두지 않아도 될 것 같다.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanFactoryUtils.java
> +		} catch (InstantiationException | IllegalAccessException | IllegalArgumentException
Exception별로 별도의 처리를 하지 않는다면 Exception 하나로 catch하는 건 어떨까?

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanScanner.java
> +	private void scanControllers() {
메소드 역할이 바뀌었으니 이름을 바꾸는 것이 좋겠다.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanScanner.java
> +	private Map<Class<?>, Object> controllers = Maps.newHashMap();
성격이 달라졌으니 rename refactoring

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/di/factory/BeanScanner.java
> +		scanControllers();
`this.controllers = scanControllers()` 가 낫지 않을까?
메소드에서 바로 초기화하는 것보다 반환을 받아 초기화하도록 개선한다면...

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +	private static final Logger logger = LoggerFactory.getLogger(JdbcManager.class);
code convetion으로 static final은 클래스 바로 아래 위치하는 것이 관례임.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +			} catch (IllegalArgumentException | IllegalAccessException | SQLException e) {
Exception을 하나로 통합.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/jdbc/JdbcManager.java
> +				e.printStackTrace();
Exception catch후 아무 일도 하지 않는 것보다 RuntimeException으로 rethrow하는 것이 그나마 나을 것 같다.
이렇게 구현해 버리면 에러가 발생했을 때 사용자에게 에러를 전달할 방법이 없다.

2017-11-13 09:36 UTC, javajigi commented on src/main/java/core/nmvc/persistence/RepositoryFactory.java
> +		annotatedClasses = new Reflections("next.model").getTypesAnnotatedWith(Repository.class);
"next.model"이라는 패키지 값은 언제라도 변경될 수 있음.
initialize() 메소드 인자로 전달하는 것은 어떨까?

2017-11-14 02:27 UTC, seulgiwendy commented
ORM API 구현이 아닌 "구현 중" 입니다. ㅎㅎ

2017-11-14 02:54 UTC, merged