Step2
code-squad/java-framework pull request #41
Opened 2018-03-25 07:45 UTC by brilliantBae

리뷰부탁드립니다.

2018-03-25 11:33 UTC, javajigi requested changes
구현잘했네. 💯 다음 단계로 지금까지 작업한 코드를 이전 코드로 reset한 후에 힌트 문서를 참고해서 다시 한번 진행해 보면 좋겠다.

2018-03-29 00:51 UTC, javajigi requested changes
구현 잘 했네. 중복 코드가 있는데 제거해 보면 좋겠다.

2018-03-29 00:51 UTC, javajigi commented on src/main/java/next/dao/JdbcTemplate.java
> +    public static void update(String query, Object... objects) throws DataAccessException {
update(String query, PreparedStatementSetter pss) 메소드와 중복 코드가 많은데 중복을 제거해 본다.

2018-03-29 00:51 UTC, javajigi commented on src/main/java/next/dao/JdbcTemplate.java
> +    public static <T> T queryForObject(String sql, RowMapper<T> rm, PreparedStatementSetter pss) throws DataAccessException {
query(String sql, RowMapper<T> rm)와의 중복을 제거해본다.

2018-03-29 00:51 UTC, javajigi commented on src/main/java/next/dao/JdbcTemplate.java
> +    public static <T> T queryForObject(String sql, RowMapper<T> rm, Object... objects) throws DataAccessException {
query(String sql, RowMapper rm)와의 중복을 제거해본다.

2018-03-29 02:02 UTC, brilliantBae commented
ddd

2018-03-29 05:32 UTC, merged